load("@bazel_tools//tools/cpp:cc_configure.bzl", "cc_configure")

cc_configure()


local_repository(
    name="parlaylib",
    path="../parlaylib/include",
)
local_repository(
    name="soa",
    path="../StructOfArrays/include",
)
local_repository(
    name="ParallelTools",
    path="../ParallelTools/",
)